# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}

# Simple workspace bezier for spatial orientation
bezier = spatial, 0.25, 1, 0.5, 1

# Expressive workspace bezier with bounce
bezier = spatialExpressive, 0.38, 1.21, 0.22, 1.00

# Apply bezier to workspaces, replace 2 with 5 for expressive
animation = workspaces, 1, 2, spatial, slidever
